### ISSUE TITLE
[Bug] Ingest must be able to deal with XML files that have an XML declaration

### ISSUE THREAD

**Issue by dariok** [dariok/wdbplus#473]
Storing a well formed file with a valid XML declaration must not fail!

- [ ] if this boils down to a wrong behaviour of `xmldb:store`, open an issue for eXist.
- [ ] as a work around, remove declaration in `wdbri:store`
- [ ] when an error is thrown by `wdbri:store`, rest-files.xql:79ff. must not be executed but the error returned

```
Caused by: org.exist.xquery.XPathException: exerr:ERROR Type error: the given string 'error storing text/xml to //db/apps/edoc/data/amwg//texts/0049.xml:
java:org.xmldb.api.base.XMLDBException: The XML parser reported a problem: fatal error at (2,6) : The processing instruction target matching "[xX][mM][lL]" is not allowed. XMLDB reported an exception while storing documentorg.xmldb.api.base.XMLDBException: The XML parser reported a problem: fatal error at (2,6) : The processing instruction target matching "[xX][mM][lL]" is not allowed.' cannot be cast to xs:anyURI [at line 80, column 7, source: /db/apps/edoc/rest/rest-files.xql]
In function:
        wdbRMi:enterMetaXML(xs:anyURI) [80:7:/db/apps/edoc/rest/ingest.xqm]
        wdbRf:storeFile(xs:string, xs:string, xs:string*) [-1:-1:/db/apps/edoc/rest/rest-files.xql]
        at org.exist.xquery.value.AnyURIValue.<init>(AnyURIValue.java:115) ~[exist-core-5.2.0.jar:5.2.0]
        at org.exist.xquery.value.StringValue.convertTo(StringValue.java:454) ~[exist-core-5.2.0.jar:5.2.0]
```

**Comment by dariok** [comment]
Check this with REST v2, Cf. #574

**Comment by dariok** [comment]
We now rely on roaster to parse the XML. With https://github.com/eeditiones/roaster/pull/107 , this will work for both POST and PUT.
